In [2]:
#Crear un arreglo de ceros de longitud 12 - ok
#Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
#Crear un arreglo que tenga los números del 10 al 49 - ok
#Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8 - VERLO
#Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
#Calcular la media de un arreglo usando np.sum
#Calcular la varianza de un arreglo usando np.sum y np.mean
#Crear un array de números aleatorios usando np.random.randn.

In [3]:
import numpy as np

In [4]:
!pip install pandas

In [5]:
!pip install numpy

In [11]:
#Crear un arreglo de ceros de longitud 12
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
#Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
nuevo_array = np.zeros(10)
nuevo_array[4 : 5] = [10]
print (nuevo_array)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [46]:
#Crear un arreglo que tenga los números del 10 al 49
array_3 = np.arange(10, 50, 1)
print (array_3)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [67]:
#Crear un arreglo 2d de shape (3, 3) que tenga los números del 0 al 8 #VER! porque linea 78 y 80 dan esas dimensiones 
array_w = [[[0,1,2],[3,4,5],[6,7,8]]]
arr2d = np.array(array_w)
arr2d

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [77]:
#Crear un arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array_w = [[[0,1,2],[3,4,5],[6,7,8]]]
arr2d = np.array(array_w)
print (arr2d)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [78]:
print(arr2d.ndim)

3


In [79]:
lista2 = [[0, 1, 3], [6, 4, 5], [9, 10, 8], [2, 7, 11]]
nuevo_arrays = np.array(lista2)
print (nuevo_arrays)

[[ 0  1  3]
 [ 6  4  5]
 [ 9 10  8]
 [ 2  7 11]]


In [80]:
print(nuevo_arrays.ndim)

2


In [96]:
#Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
abc = (np.random.randn(100))
print(abc)

[-0.6357036   1.5473429  -1.33036924  0.8673774  -0.08304308  0.38998617
  0.35028046  0.51596978  0.48792055 -0.82612744 -0.89560432  1.12963509
 -0.29014497 -1.71019066 -0.07190275  1.9191053   0.86493209 -1.3117699
  0.56583445  1.10475492 -1.66953885 -0.86327694 -0.30567437  1.45210341
  0.48157995  1.01529156  1.18786008 -2.1646     -1.01654007 -0.04618058
 -0.38924065 -0.1880749   0.75275839 -0.25704299  1.85111643  0.43750505
 -0.11849225  1.75667925 -0.51803231 -1.85169013  0.52272175  0.85472857
  1.37902886  0.36558723 -2.48727448  0.82624601  2.06902698 -0.2553743
 -0.33582367 -1.97107243 -1.65207035  2.5715501  -0.37451905 -0.25829549
 -1.18693561 -0.02169687  0.27923963  0.22482383  1.27844345  0.30716172
  0.76476873  1.23821822  0.55249419 -0.25151786  0.27903046  0.44671191
  0.53073283 -0.60742975  0.1590039  -0.10798607 -1.59863403  1.23623529
 -0.57533935  0.43932999  0.7314022   0.27099412  1.38960835  0.46500098
 -0.7161313  -0.41688593  0.46400459  0.29041495 -1.7

In [97]:
np.var(abc) #varianza

1.030218706221878

In [98]:
np.mean(abc) #media

0.015540466395877632

In [101]:
#Calcular la media de un arreglo usando np.sum
nuevamedia = np.sum(abc)/(abc.size)
print(nuevamedia)

0.015540466395877632


In [105]:
#Calcular la varianza de un arreglo usando np.sum y np.mean PENDIENTE
nuevavarianza = np.sum(abc)/(np.mean(abc))
print(nuevavarianza)

100.0


In [112]:
#Crear un array de números aleatorios usando np.random.randn.
xyz = (np.random.randn(25))
print (xyz)

[-1.95323844  0.79150122 -0.33484549  0.80697574 -1.03732579  0.4766134
  2.50015796 -0.91814558 -0.31013058  2.47421265  1.13696422  1.05438796
  1.64981269 -1.47369867 -0.35551908 -0.60531798 -0.82920434 -0.21752418
  0.13697884 -1.38294784  0.15882398 -0.90444538  2.1575329  -2.03879077
  0.5251731 ]
